### ISSUE TITLE
problem about log deleted messages

### ISSUE THREAD

**Issue by RabbitYuKu** [soranoo/Discord-Logger#1]
Are you sure you want to do log deleted messages?

**Comment by soranoo** [comment]
According to the [Discord Gateway documents](https://discord.com/developers/docs/topics/gateway), getting the deleted message is still technically impossible.

The program will be updated when it is possible.

References:
[[Discord Gateway #message-delete]](https://discord.com/developers/docs/topics/gateway#message-delete)

**Comment by RabbitYuKu** [comment]
Alr

**Comment by RabbitYuKu** [comment]
made your technically impossible thing become possible
